[tool.poetry]
name = "parallel-requests"
version = "0.1.5"
description = ""
authors = ["Volker Lorrmann <volker.lorrmann@gmail.com>"]
readme = "README.md"
packages = [{ include = "parallel_requests", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
asyncio = "^3.4.3"
pandas = "^1.4.4"
requests = "^2.28.1"
python-dotenv = "^0.21.0"
asyncer = "^0.0.2"
loguru = "^0.6.0"
tqdm = "^4.64.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
