[tool.poetry]
name = "async-requests"
version = "0.1.0"
description = ""
authors = ["Volker Lorrmann <volker.lorrmann@gmail.com>"]
readme = "README.md"
packages = [{include = "async_requests", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8.1"
asyncio = "^3.4.3"
pandas = "^1.4.4"
tenacity = "^8.0.1"
requests = "^2.28.1"
dotenv = "^0.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
